services:
  web:
    build:
      context: ./typeracer_clone_django/
      dockerfile: ./Dockerfile
    command: >
      sh -c "
             python manage.py migrate --noinput &&
             python populate_db.py &&
             python manage.py collectstatic --noinput &&
             ( python manage.py createsuperuser --noinput || true) &&
             uvicorn config.asgi:application --host 0.0.0.0 --port 8001"
    volumes:
      - ./typeracer_clone_django:/app
    expose:
      - "8001"
    env_file:
      - ../secrets/.env
    external_links:
      - db:db
    depends_on:
      - redis
      - db
    networks:
      - extnetwork

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./typeracer_clone_django/staticfiles:/staticfiles
      - ./typeracer_clone_react:/app
    ports:
      - "8002:8002"
    expose:
      - "8002"
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=neotyper.iljuhenson.com
      - VIRTUAL_PORT=8002
      - LETSENCRYPT_HOST=neotyper.iljuhenson.com
    networks:
      - extnetwork

networks:
  extnetwork:
    name: server_network
    external: true
