# Generated by Django 4.2 on 2023-07-01 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import race_handler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes_interface', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.CharField(default=race_handler.models.generate_short_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('w', 'waiting'), ('t', 'on timer'), ('s', 'started'), ('f', 'finished')], default='w', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_races', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='races', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='quotes_interface.quotes')),
            ],
        ),
        migrations.CreateModel(
            name='RaceStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('time_racing', models.DurationField(blank=True, null=True)),
                ('place', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races_statistics', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statistics', to='race_handler.race')),
            ],
        ),
    ]
