# Generated by Django 4.2 on 2023-04-23 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('race_handler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racestatistics',
            name='user',
        ),
        migrations.AddField(
            model_name='race',
            name='participants',
            field=models.ManyToManyField(related_name='races', to=settings.AUTH_USER_MODEL),
        ),
    ]
