# Generated by Django 4.2 on 2023-04-25 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race_handler', '0002_remove_racestatistics_user_race_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='status',
            field=models.CharField(choices=[('w', 'waiting'), ('t', 'on timer'), ('s', 'started'), ('f', 'finished')], default='w', max_length=1),
        ),
    ]
