# Generated by Django 4.2.3 on 2025-02-28 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('race_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participant_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('vehicle_look', models.CharField(choices=[('b', 'bicycle'), ('c', 'car'), ('p', 'person')], default='b', max_length=1)),
            ],
        ),
    ]
